# Site settings
course_name: TEMABio
course_description: "Treinamento, Equipamento e Mentoria em Monitoramento Acústico da Biodiversidade"
course_semester: "Pantanal 2024-2025"

baseurl: "/Pantanal2024" # the subpath of your site, e.g. /blog/
url: "http://TEMABio.github.io/" # the base hostname & protocol for your site

schoolname: "K. Lisa Yang Center for Conservation Bioacoustics"
schoolurl: "https://www.birds.cornell.edu/ccb"
twitter_username: CornellSounds

address: |
    159 Sapsucker Woods Rd
    14850 Ithaca, NY

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
